package:
  name: glibc
  version: 2.36
  epoch: 0
  description: "the GNU C library"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: GPL-3.0-or-later
  dependencies:
    runtime:
      - wolfi-baselayout
      - linux-headers
  scriptlets:
    trigger:
      paths:
        - /lib
        - /lib64
        - /usr/lib
        - /usr/lib64
      script: |
        #!/bin/busybox sh
        /sbin/ldconfig
environment:
  contents:
    repositories:
      - https://mirrors.edge.kernel.org/alpine/edge/main
      - https://packages.wolfi.dev/bootstrap/stage1
    keyring:
      - /usr/share/apk/keys/x86_64/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
      - /usr/share/apk/keys/x86_64/alpine-devel@lists.alpinelinux.org-5261cecb.rsa.pub
      - /usr/share/apk/keys/x86_64/alpine-devel@lists.alpinelinux.org-6165ee59.rsa.pub
      - /usr/share/apk/keys/aarch64/alpine-devel@lists.alpinelinux.org-58199dcc.rsa.pub
      - /usr/share/apk/keys/aarch64/alpine-devel@lists.alpinelinux.org-616ae350.rsa.pub
      - https://packages.wolfi.dev/bootstrap/stage1/wolfi-signing.rsa.pub
    packages:
      - alpine-baselayout-data
      - busybox
      - build-base
      - scanelf
      - ssl_client
      - ca-certificates-bundle
      - texinfo
      - gmp-dev
      - mpfr-dev
      - mpc1-dev
      - zlib-dev
      - gawk
      - zip
      - bison
      - flex
      - cross-binutils-stage1
      - cross-gcc-stage1
      - cross-linux-headers
      - python3
      - grep
pipeline:
  - uses: fetch
    with:
      uri: http://ftp.gnu.org/gnu/libc/glibc-${{package.version}}.tar.gz
      expected-sha256: 02efa6ffbbaf3e10e88f16818a862608d04b0ef838c66f6025ae120530792c9c
  - name: 'Fix compatibility with GNU make 4.4'
    runs: |
      sed '/MAKEFLAGS :=/s/)r/) -r/' -i Makerules
  - name: 'Set up build directory'
    runs: |
      mkdir build
  - name: 'Configure glibc'
    runs: |
      cd build
      ../configure \
        --prefix=/ \
        --libdir=/lib \
        --includedir=/usr/include \
        --host=${{cross.triplet.gnu.glibc}} \
        --build=$(../config.guess) \
        --disable-nls \
        --disable-werror \
        --enable-kernel=4.9 \
        --with-sysroot=/usr/${{cross.triplet.gnu.glibc}} \
        --with-headers=/usr/${{cross.triplet.gnu.glibc}}/usr/include \
        --disable-nls
  - runs: |
      make -C build -j$(nproc)
  - runs: |
      make -C build -j$(nproc) install DESTDIR="${{targets.destdir}}"
  - name: "Set up ldconfig"
    runs: |
      cp vendor/ld.so.conf "${{targets.destdir}}"/etc/ld.so.conf
  - name: 'Clean up documentation'
    runs: |
      rm -rf ${{targets.destdir}}/usr/share/info
  - uses: strip
