package:
  name: libstdc++
  version: 12.2.0
  epoch: 0
  description: "the GNU C++ STL implementation"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: LGPL-3.0-or-later
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://mirrors.edge.kernel.org/alpine/edge/main
      - https://packages.wolfi.dev/bootstrap/stage1
    keyring:
      - /usr/share/apk/keys/x86_64/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
      - /usr/share/apk/keys/x86_64/alpine-devel@lists.alpinelinux.org-5261cecb.rsa.pub
      - /usr/share/apk/keys/x86_64/alpine-devel@lists.alpinelinux.org-6165ee59.rsa.pub
      - https://packages.wolfi.dev/bootstrap/stage1/wolfi-signing.rsa.pub
    packages:
      - alpine-baselayout-data
      - busybox
      - build-base
      - scanelf
      - ssl_client
      - ca-certificates-bundle
      - texinfo
      - gmp-dev
      - mpfr-dev
      - mpc1-dev
      - zlib-dev
      - gawk
      - zip
      - bison
      - flex
      - cross-binutils-stage1
      - cross-gcc-stage1
      - cross-glibc-stage1

pipeline:
  - uses: fetch
    with:
      uri: https://gcc.gnu.org/pub/gcc/releases/gcc-${{package.version}}/gcc-${{package.version}}.tar.gz
      expected-sha256: ac6b317eb4d25444d87cf29c0d141dedc1323a1833ec9995211b13e1a851261c
  - name: 'Set up build directory'
    runs: |
      mkdir build
  - name: 'Configure libstdc++'
    runs: |
      cd build
      ../libstdc++-v3/configure \
        --prefix=/usr \
        --libdir=/lib \
        --host=${{cross.triplet.gnu.glibc}} \
        --target=${{cross.triplet.gnu.glibc}} \
        --build=$(../config.guess) \
        --disable-nls \
        --disable-multilib \
        --disable-werror \
        --disable-libstdcxx-pch \
        --with-gxx-include-dir=/usr/include/c++/${{package.version}}
  - runs: |
      make -C build -j$(nproc)
  - runs: |
      make -C build -j$(nproc) install DESTDIR="${{targets.destdir}}"
  - name: 'Clean up documentation'
    runs: |
      rm -rf ${{targets.destdir}}/usr/share/info
  - uses: strip
