package:
  name: zlib
  version: 1.2.13
  epoch: 0
  description: "a library implementing the zlib compression algorithms"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: MPL-2.0 AND MIT
  dependencies:
    runtime:
environment:
  contents:
    repositories:
      - https://mirrors.edge.kernel.org/alpine/edge/main
      - https://packages.wolfi.dev/bootstrap/stage1
    keyring:
      - /usr/share/apk/keys/x86_64/alpine-devel@lists.alpinelinux.org-4a6a0840.rsa.pub
      - /usr/share/apk/keys/x86_64/alpine-devel@lists.alpinelinux.org-5261cecb.rsa.pub
      - /usr/share/apk/keys/x86_64/alpine-devel@lists.alpinelinux.org-6165ee59.rsa.pub
      - /usr/share/apk/keys/aarch64/alpine-devel@lists.alpinelinux.org-58199dcc.rsa.pub
      - /usr/share/apk/keys/aarch64/alpine-devel@lists.alpinelinux.org-616ae350.rsa.pub
      - /usr/share/apk/keys/armv7/alpine-devel@lists.alpinelinux.org-524d27bb.rsa.pub
      - /usr/share/apk/keys/armv7/alpine-devel@lists.alpinelinux.org-616adfeb.rsa.pub
      - https://packages.wolfi.dev/bootstrap/stage1/wolfi-signing.rsa.pub
    packages:
      - alpine-baselayout
      - busybox
      - perl
      - ca-certificates-bundle
      - cross-gcc-stage1
      - cross-binutils-stage1
      - cross-glibc-stage1
      - cross-linux-headers
pipeline:
  - uses: fetch
    with:
      uri: https://zlib.net/zlib-${{package.version}}.tar.gz
      expected-sha256: b3a24de97a8fdbc835b9833169501030b8977031bcb54b3b3ac13740f846ab30
  - runs: |
      CHOST="${{cross.triplet.gnu.glibc}}" ./configure \
        --prefix=/usr \
        --libdir=/lib \
        --shared
  - uses: autoconf/make
  - runs: |
      make install pkgconfigdir="/usr/lib/pkgconfig" DESTDIR="${{targets.destdir}}"
subpackages:
  - name: "cross-zlib"
    pipeline:
      - runs: |
          make install pkgconfigdir="/usr/lib/pkgconfig" DESTDIR="${{targets.subpkgdir}}/usr/${{cross.triplet.gnu.glibc}}"
    options:
      no-provides: true
      no-depends: true
      no-commands: true
